name: carSim69
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2022.12.7=py37haa95532_0
  - openssl=1.1.1w=h2bbff1b_0
  - pip=22.3.1=py37haa95532_0
  - python=3.7.9=h60c2a47_0
  - setuptools=65.6.3=py37haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.38.4=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.5.2
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - cycler==0.11.0
      - dnspython==1.16.0
      - eventlet==0.25.1
      - flask==1.1.2
      - flatbuffers==25.9.23
      - fonttools==4.38.0
      - gast==0.6.0
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.1.1
      - grpcio==1.62.3
      - h5py==3.8.0
      - idna==3.10
      - imageio==2.31.2
      - imgaug==0.4.0
      - importlib-metadata==6.7.0
      - itsdangerous==2.0.1
      - jinja2==2.11.3
      - joblib==1.3.2
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.4.4
      - markupsafe==2.0.1
      - matplotlib==3.5.3
      - monotonic==1.6
      - networkx==2.6.3
      - numpy==1.21.6
      - oauthlib==3.2.2
      - opencv-python==4.12.0.88
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - protobuf==3.20.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-engineio==3.13.2
      - python-socketio==4.6.1
      - pytz==2025.2
      - pywavelets==1.3.0
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - shapely==2.0.7
      - six==1.17.0
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.8.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - tf-estimator-nightly==2.8.0.dev2021122109
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - werkzeug==2.0.3
      - wrapt==1.16.0
      - zipp==3.15.0
prefix: C:\Users\Tejas\.conda\envs\carSim4
